### ISSUE TITLE
Acquiring for reconstruction script for your compression method

### ISSUE THREAD

**Issue by wcjj1236** [UCDvision/compact3d#10]
Hey, Would you mind providing me with the reconstruction or restoring python scripty for you compression method. I mean converting point_cloud.ply, kmeans_centers.pth, kmeans_args.npy, and kmeans_inds.bin into one point_cloud.ply file. In that case, I can directly open the rebuildt 3DGS with SIBR viewer.

**Comment by klnavaneet** [comment]
Hi. Thank you for your interest in our work. We have added support for conversion to a single ply file. Check out the 'convert to non-quantized model' section of the ReadMe.
