### ISSUE TITLE
How to visualize the trained model with SIBR viewer?

### ISSUE THREAD

**Issue by Zafiirah13** [UCDvision/compact3d#11]
Hello,

Would it be possible to provide details on how to reconstruct the 3DGS model from the compressed file and view it in SIBR viewer?

I have downloaded your MipNerf-360 trained models [here](https://drive.google.com/drive/folders/14WVjkqmkhbJQ-IEM_Un0YTTiB2jKJqQD) but I'm unable to view it with SIBR viewer

Using this command I use: 
`SIBR_gaussianViewer_app.exe -m "C:\Users\Downloads\compgs_4k\e041_a_kmeans_512_10it_st15000_tot30000_fr100diff_last5k\mipnerf360\bonsai\"`

And here is the error:
![image](https://github.com/UCDvision/compact3d/assets/20860570/76aa4875-792c-4db0-8971-a9806168c4bd)
![image](https://github.com/UCDvision/compact3d/assets/20860570/34231375-7b92-465e-8b8c-ca368e36d72d)

Note that it is not about memory issue - I managed to visualize uncompressed models (bigger file size) of original 3DGS models.

Is there something I need to do before viewing the compressed trained models? Thank you

**Comment by klnavaneet** [comment]
Hi. You will need to convert the quantized model to a non-quantized ply file to use the sibr viewer. We have added support for this. Check out the 'convert to non-quantized model' section of the ReadMe.

**Comment by Zafiirah13** [comment]
Thank you for adding this feature, it works well.
