### ISSUE TITLE
Opacity regularization is broken

### ISSUE THREAD

**Issue by idilsulo** [UCDvision/compact3d#12]
Hello - I'd like to run Compact3D with `opacity_reg` parameter after the recent update on July 31, 2024. However, this change seems to be breaking since when I run the bash script `run.sh`, I get the following error when the execution hits the opacity regularization at the 16000th iteration:
```
[ITER 16000] Evaluating train: L1 0.01976204663515091 PSNR 30.19481582641602 [08/08 17:43:24]
Num Gaussians:  616981 [08/08 17:43:24]
Traceback (most recent call last):
  File "train_kmeans.py", line 410, in <module>
    args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args)
  File "train_kmeans.py", line 225, in training
    gaussians.prune(0.005, scene.cameras_extent, size_threshold)
AttributeError: 'GaussianModel' object has no attribute 'prune'
```
It seems like the version of the method with opacity regularization uses a method named `prune` under the `GaussianModel` which is not available within this or the original 3D gaussian splatting code base.

**Comment by klnavaneet** [comment]
Hi @idilsulo. Thanks! We have updated the ``gaussian_model.py`` code to add the function.
