### ISSUE TITLE
AttributeError: 'GaussianModel' object has no attribute 'get_opacity_nq'

### ISSUE THREAD

**Issue by YihangChen-ee** [UCDvision/compact3d#16]
Hi, good work!
I encountered this Error: AttributeError: 'GaussianModel' object has no attribute 'get_opacity_nq'.
It seems the variable self.get_opacity_nq  is not defined in the class: GaussianModel.

How to fix this problem?

**Comment by klnavaneet** [comment]
Hi @YihangChen-ee . The variable self.get_opacity_nq just needs to be modified to self.get_opacity. I have made the change to the repo. Thanks for pointing it out!
