### ISSUE TITLE
checkpoint/pretrained model

### ISSUE THREAD

**Issue by robinsonkwame** [UCDvision/compact3d#4]
Love this work! Wanted to ask if there was a checkpoint or pretrained model available.

**Comment by klnavaneet** [comment]
Hi. Thank you for your interest. Pretrained models are now available [here](https://drive.google.com/drive/folders/14WVjkqmkhbJQ-IEM_Un0YTTiB2jKJqQD?usp=sharing).

**Comment by cfchi** [comment]
@klnavaneet Hi, thanks for the great code.
Could you kindly consider releasing the "CompGS 4k, Int16" trained model? 
Alternatively, could you provide relevant training parameters for it? 
Your assistance in this matter would be greatly appreciated.

**Comment by klnavaneet** [comment]
@cfchi Hi. For bit quantization experiments with CompGS (including CompGS 4k, Int16), we use post-training quantization. The model training is done without any changes in precision and quantization is performed during inference. So the pre-trained models for CompGS 4k, Int16 are the same ones as for CompGS 4k. 
PS: we will be updating the work with 4-5x smaller models very soon! stay tuned.
