### ISSUE TITLE
kmeans.cls_ids causes division by zero error.

### ISSUE THREAD

**Issue by 00qnavry00** [UCDvision/compact3d#5]
When I'm training and reach about 23% where save_kmeans() is called, I get a division by zero error on line 244 in train_kmeans.py

244     n_bits = int(np.ceil(np.log2(len(kmeans.cls_ids))))

I checked the traceback and kmeans.cls_ids returned an empty tensor array similar to its instantiation in line 20 in kmeans_quantize.py

20        self.cls_ids = torch.empty(0)

**Comment by dizhenhuoshan** [comment]
Same problem for me with the given run.sh.

**Comment by klnavaneet** [comment]
Hi. Thank you for your interest in our work. The error was due to a minor bug - the kmeans params were being saved before the kmeans based training is started. It is fixed now.
